SFDC=* NOT SFDC IN ("DC13", "DC25")
splunk_server_group = *_indexers 
(host="*" OR servername="*")
index=hcm_sac_app
(sourcetype = app_log_sac)
sac_app_log_level = ERROR

| rex field=_raw "^.*?\]\s([a-z][\.])*(?<component>.*?)\s+:\s\["
| rex field=_raw "^(?<skip>(?:[^\]\n]*\]){3})\s*(?P<err_message>.+)" 

| eval err_message=case(like(err_message,"[129]: transaction rolled back by an internal error: Allocation failed%"),"([129]: transaction rolled back by an internal error: Allocation failed)|(UNKNOWN ERROR) [129]: transaction rolled back by an internal error",like(err_message,"%Cannot rollback transaction%"),"(Cannot rollback transaction)|(UNKNOWN ERROR) Cannot rollback transaction",like(err_message,"%Connection to database server lost%"),"(Connection to database server lost)|IOException: Connection reset by peer",like(err_message,"%Error during processSynchronization%"),"(Error during processSynchronization)|Error during processSynchronization",like(err_message,"%Error executing SQL%PooledConnection has already been closed%"),"(Error executing SQL...PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"%Error node is not null"),"(Error node is not null)|(UNKNOWN ERROR) Error node is not null",like(err_message,"%ERROR_CODE 6006 Error while injecting%"),"(ERROR_CODE 6006 Error while injecting)|(UNKNOWN ERROR) ERROR_CODE 6006 Error while injecting ExtendedDimensions",like(err_message,"%Exception while processing variables"),"(Exception while processing variables)|Exception while processing variables",like(err_message,"%Failed to get the server information%"),"(Failed to get the server information)|Failed to get the server information",like(err_message,"%java.sql.SQLException: PooledConnection has already been closed%"),"(PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"%liquibase.exception.DatabaseException: java.sql.SQLException: PooledConnection has already been closed%"),"(PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"%liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: PooledConnection has already been closed%"),"(PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"%Query definition missing%"),"(Query definition missing)|(UNKNOWN ERROR) Query definition missing",like(err_message,"%RTEException: Connection to database server lost%error 104 - Connection reset"),"(RTEException: Connection to database server lost...error 104 - Connection reset)|IOException: Connection reset by peer",like(err_message,"%IOException: error 104 - Connection reset by peer"),"(IOException: error 104 - Connection reset by peer)|IOException: Connection reset by peer",like(err_message,"%Unhandled error in servlet filter processing%"),"(Unhandled error in servlet filter processing)|Unhandled Error",like(err_message,"403 Forbidden%"),"(403 Forbidden)|403 Forbidden",like(err_message,"406 Not Acceptable%"),"(406 Not Acceptable)|406 Not Acceptable",like(err_message,"500 Internal Server Error%"),"(500 Internal Server Error)|500 Internal Server Error",like(err_message,"502 Bad Gateway%"),"(502 Bad Gateway)|502 Bad Gateway:",like(err_message,"502%the server%received an invalid response%"),"(502 the server received an invalid response)|502 Bad Gateway:",like(err_message,"Access to the object%is not allowed."),"(Access to the object is not allowed.)|Access object not allowed",like(err_message,"Application exception overridden by rollback exception%"),"(Application exception overridden by rollback exception)|(UNKNOWN ERROR) Application exception overridden by rollback exception",like(err_message,"Application run failed%"),"(Application run failed)|(UNKNOWN ERROR) Application run failed",like(err_message,"Bad server response%"),"(Bad server response)|(UNKNOWN ERROR) Bad server response",like(err_message,"Calc view recovery is not support for this query type%"),"(Calc view recovery is not support for this query type)|(UNKNOWN ERROR) Calc view recovery is not support for this query type",like(err_message,"Calculation view not active%"),"(Calculation view not active)|(UNKNOWN ERROR) Calculation view not active",like(err_message,"Call to read audit log failed%"),"(Call to read audit log failed)|(UNKNOWN ERROR) Call to read audit log failed",like(err_message,"Cannot forward to error page for request%"),"(Cannot forward to error page for request)|(UNKNOWN ERROR) Cannot forward to error page for request",like(err_message,"Cannot get database name%"),"(Cannot get database name)|(UNKNOWN ERROR) Cannot get database name",like(err_message,"Cannot rollback transaction%"),"(Cannot rollback transaction)|(UNKNOWN ERROR) Cannot rollback transaction",like(err_message,"com.sap.db.jdbc.exceptions.RTEException: Connection to database server lost; check server and network status [System error: java.io.IOException: error 104 - Connection reset by peer]"),"(IOException: error 104 - Connection reset by peer)|IOException: Connection reset by peer",like(err_message,"Connection to database server lost; check server and network status [System error: java.io.IOException: error 104 - Connection reset by peer]"),"(IOException: error 104 - Connection reset by peer)|IOException: Connection reset by peer",like(err_message,"Connection to database server lost%"),"(Connection to database server lost)|(UNKNOWN ERROR) Connection to database server lost",like(err_message,"Context field%for GDPR audit logging not provided%"),"(Context field for GDPR audit logging not provided)|(UNKNOWN ERROR) Context field not provided",like(err_message,"Data source field list doesn't have the field%"),"(Data source field list doesn't have the field)|(UNKNOWN ERROR) Data source field list doesn't have the field",like(err_message,"Error : "),"(Error :)|(UNKNOWN ERROR) ERROR-5008",like(err_message,"%The parallel execution limit per tenant has been exceeded%"),"(The parallel execution limit per tenant has been exceeded)|Parallel execution limit per tenant has been exceeded",like(err_message,"ERROR 4501 Validation end point timed out%"),"(ERROR 4501 Validation end point timed out)|(UNKNOWN ERROR) ERROR 4501 Validation end point timed out",like(err_message,"ERROR 4502 Response of external server cannot be parsed%"),"(ERROR 4502 Response of external server cannot be parsed)|(UNKNOWN ERROR) ERROR 4502 Response of external server cannot be parsed",like(err_message,"ERROR 4505 Query Builder Validation Internal Server error on the LoB end point side%"),"(ERROR 4505 Query Builder Validation Internal Server error on the LoB end point side%)|(UNKNOWN ERROR) ERROR 4505 Query Builder Validation Internal Server error",like(err_message,"Error Code : 3108 Cannot get user authentication information%"),"(Error Code : 3108 Cannot get user authentication information)|(UNKNOWN ERROR) Error Code : 3108 Cannot get user authentication information",like(err_message,"Error Code : 3111 Token decryption failed"),"(Error Code : 3111 Token decryption failed)|Token Decryption",like(err_message,"Error Code : 4521 Not authorized to request metadata"),"(Error Code : 4521 Not authorized to request metadata)|(UNKNOWN ERROR) Error Code : 4521 Not authorized to request metadata",like(err_message,"ERROR CODE%missing GDPR context field"),"(ERROR CODE : missing GDPR context field)|(UNKNOWN ERROR) InaQuery is missing GDPR context field",like(err_message,"Error creating DB connection%"),"(Error creating DB connection)|(UNKNOWN ERROR) Error creating DB connection",like(err_message,"Error during processSynchronization%"),"(Error during processSynchronization)|Error during processSynchronization",like(err_message,"Error executing SQL%"),"(Error executing SQL)|PooledConnection has already been closed",like(err_message,"Error%Query has error while exporting"),"(Query has error while exporting)|(UNKNOWN ERROR) Query has error while exporting",like(err_message,"Error from HanaFileAPI%Error while writing file%"),"(Error while writing file)|(UNKNOWN ERROR) Error while writing file",like(err_message,"Error in GenericRemoteAPI: GET%"),"(Error in GenericRemoteAPI: GET)|(UNKNOWN ERROR) Error in GenericRemoteAPI: GET",like(err_message,"Error in GenericRemoteAPI: POST%"),"(Error in GenericRemoteAPI: POST)|(UNKNOWN ERROR) Error in GenericRemoteAPI: POST",like(err_message,"Error in Request Processing: Error while writing file"),"(Error in Request Processing: Error while writing file)|(UNKNOWN ERROR) Error in Request Processing",like(err_message,"Error node is not null"),"(Error node is not null)|(UNKNOWN ERROR) Error node is not null",like(err_message,"Error occured while extracting story execution details%"),"(Error occured while extracting story execution details)|Execution Details Extraction",like(err_message,"Error while writing csv export response to DB"),"(Error while writing csv export response to DB)|Error writing csv export response",like(err_message,"ERROR_CODE 3512 Exception on creating dataSource"),"(ERROR_CODE 3512 Exception on creating dataSource)|(UNKNOWN ERROR) ERROR_CODE 3512 Exception on creating dataSource",like(err_message,"ERROR_CODE 3516 Cannot find dbPoolId in ServerConfiguration"),"(ERROR_CODE 3516 Cannot find dbPoolId in ServerConfiguration)|(UNKNOWN ERROR) ERROR_CODE 3516 Cannot find dbPoolId in ServerConfiguration",like(err_message,"ERROR_CODE 3518 Cannot get DB Connection from DataSource%"),"(ERROR_CODE 3518 Cannot get DB Connection from DataSource)|(UNKNOWN ERROR) ERROR_CODE 3518 Cannot get DB Connection from DataSource",like(err_message,"ERROR_CODE 42010 Unsupported operation%"),"(ERROR_CODE 42010 Unsupported operation)|(UNKNOWN ERROR) ERROR_CODE 42010 Unsupported operation : CustomDimension1 is missing",like(err_message,"ERROR_CODE 42014 Caught exception : exception 1000002: Allocation failed%"),"(ERROR_CODE 42014 Caught exception : exception 1000002: Allocation failed)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 1000013%"),"(ERROR_CODE 42014 Caught exception : exception 1000013: failed to execute all requests )|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 1000087%"),"(ERROR_CODE 42014 Caught exception : exception 1000087: basic_ios::clear)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42012%"),"(ERROR_CODE 42014 Caught exception : exception 42012: The wrong value type was requested)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42018%"),"(ERROR_CODE 42014 Caught exception : exception 42018: Internal error occurred while processing)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42111%"),"(ERROR_CODE 42014 Caught exception : exception 42111: SQL Error)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42129%"),"(ERROR_CODE 42014 Caught exception : exception 42129: Data failed to persist successfully)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42208%"),"(ERROR_CODE 42014 Caught exception : exception 42208: Can't read the view)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42218%"),"(ERROR_CODE 42014 Caught exception : exception 42218: The Blending mapping is wrongly defined)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42223%"),"(ERROR_CODE 42014 Caught exception : exception 42223: Blending failed due to internal error)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42422%"),"(ERROR_CODE 42014 Caught exception : exception 42422: The operation in the formula operator is invalid)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42432%"),"(ERROR_CODE 42014 Caught exception : exception 42432: Dimension attribute referenced in view is not defined)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42445%"),"(ERROR_CODE 42014 Caught exception : exception 42445: A field name in a filter must be a view column or dimension)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42492%"),"(ERROR_CODE 42014 Caught exception : exception 42492: The column names are empty)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42556%"),"(ERROR_CODE 42014 Caught exception : exception 42556: Extended dimension processing error)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42567%"),"(ERROR_CODE 42014 Caught exception : exception 42567: Error during formula evaluation)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000002%"),"(ERROR_CODE 42014 Caught exception : exception 70000002: general error)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000004%"),"(ERROR_CODE 42014 Caught exception : exception 70000004: cannot allocate enough memory)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000009%"),"(ERROR_CODE 42014 Caught exception : exception 70000009: Memory allocation failed)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000022%"),"(ERROR_CODE 42014 Caught exception : exception 70000022: statement recompile required)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000258%"),"(ERROR_CODE 42014 Caught exception : exception 70000258: insufficient privilege)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000259: invalid table name%"),"(ERROR_CODE 42014 Caught exception : exception 70000259: invalid table name)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000260: invalid column name%"),"(ERROR_CODE 42014 Caught exception : exception 70000260: invalid column name)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000264: invalid datatype%"),"(ERROR_CODE 42014 Caught exception : exception 70000264: invalid datatype)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000303: invalid DATE, TIME or TIMESTAMP value%"),"(ERROR_CODE 42014 Caught exception : exception 70000303: invalid DATE, TIME or TIMESTAMP value)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000304: division by zero undefined%"),"(ERROR_CODE 42014 Caught exception : exception 70000304: division by zero undefined)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000314: numeric overflow%"),"(ERROR_CODE 42014 Caught exception : exception 70000314: numeric overflow)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000339: invalid number%"),"(ERROR_CODE 42014 Caught exception : exception 70000339: invalid number)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000391: invalidated view%"),"(ERROR_CODE 42014 Caught exception : exception 70000391: invalidated view)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70002048: column store error%"),"(ERROR_CODE 42014 Caught exception : exception 70002048: column store error)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70002620: executor%"),"(ERROR_CODE 42014 Caught exception : exception 70002620: executor)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42014 Caught exception : exception 70034051: Error during plan execution%"),"(ERROR_CODE 42014 Caught exception : exception 70034051: Error during plan execution)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception",like(err_message,"ERROR_CODE 42100 The DataSource is invalid%"),"(ERROR_CODE 42100 The DataSource is invalid)|(UNKNOWN ERROR) ERROR_CODE 42100 The DataSource is invalid : SQL is invalid, see trace for more details",like(err_message,"ERROR_CODE 42111 SQL Error%"),"(ERROR_CODE 42111 SQL Error)|(UNKNOWN ERROR) ERROR_CODE 42111 SQL Error : Allocation failed",like(err_message,"ERROR_CODE 42129 Data failed to persist successfully%"),"(ERROR_CODE 42129 Data failed to persist successfully)|(UNKNOWN ERROR) ERROR_CODE 42129 Data failed to persist successfully",like(err_message,"ERROR_CODE 42201 Column not found%"),"(ERROR_CODE 42201 Column not found)|(UNKNOWN ERROR) ERROR_CODE 42201 Column not found",like(err_message,"ERROR_CODE 42208 Can't read the view%"),"(ERROR_CODE 42208 Can't read the view)|(UNKNOWN ERROR) ERROR_CODE 42208 Can't read the view",like(err_message,"ERROR_CODE 42218 The Blending mapping is wrongly defined%"),"(ERROR_CODE 42218 The Blending mapping is wrongly defined)|(UNKNOWN ERROR) ERROR_CODE 42218 The Blending mapping is wrongly defined",like(err_message,"ERROR_CODE 42227 One of the blending source queries returned an empty result%"),"(ERROR_CODE 42227 One of the blending source queries returned an empty result)|(UNKNOWN ERROR) ERROR_CODE 42227 One of the blending source queries returned an empty result",like(err_message,"ERROR_CODE 42420 The aggregation type is invalid%"),"(ERROR_CODE 42420 The aggregation type is invalid)|(UNKNOWN ERROR) ERROR_CODE 42420 The aggregation type is invalid",like(err_message,"ERROR_CODE 42473 A non-empty value must be used in the comparison"),"(ERROR_CODE 42473 A non-empty value must be used in the comparison)|(UNKNOWN ERROR) ERROR_CODE 42473 A non-empty value must be used in the comparison",like(err_message,"ERROR_CODE 42474 The view doesn't contain the measure%"),"(ERROR_CODE 42474 The view doesn't contain the measure)|(UNKNOWN ERROR) ERROR_CODE 42474 The view doesn't contain the measure",like(err_message,"ERROR_CODE 42494 CustomDimension%must have one measure only"),"(ERROR_CODE 42494 CustomDimension must have one measure only)|(UNKNOWN ERROR) ERROR_CODE 42494 CustomDimension on axis must have one measure only",like(err_message,"ERROR_CODE 42515 The aggregation type is not allowed for the data type of the measure%"),"(ERROR_CODE 42515 The aggregation type is not allowed for the data type of the measure)|(UNKNOWN ERROR) ERROR_CODE 42515 The aggregation type is not allowed for the data type of the measure",like(err_message,"ERROR_CODE 42518 Inconsistent state%"),"(ERROR_CODE 42518 Inconsistent state)|(UNKNOWN ERROR) ERROR_CODE 42518 Inconsistent state",like(err_message,"ERROR_CODE 42556 Extended dimension processing error%"),"(ERROR_CODE 42556 Extended dimension processing error)|(UNKNOWN ERROR) ERROR_CODE 42556 Extended dimension processing error",like(err_message,"ERROR_CODE 42560 Invalid default aggregation type used%"),"(ERROR_CODE 42560 Invalid default aggregation type used)|(UNKNOWN ERROR) ERROR_CODE 42560 Invalid default aggregation type used",like(err_message,"ERROR_CODE 42561 At least one exception aggregation dimension must be used%"),"(ERROR_CODE 42561 At least one exception aggregation dimension must be used)|(UNKNOWN ERROR) ERROR_CODE 42561 At least one exception aggregation dimension must be used",like(err_message,"ERROR_CODE 42581 Invalid sort definition%"),"(ERROR_CODE 42581 Invalid sort definition)|(UNKNOWN ERROR) ERROR_CODE 42581 Invalid sort definition",like(err_message,"ERROR_CODE 42709 The selection returned more records than the limit in MaxResultRecords%"),"(ERROR_CODE 42709 The selection returned more records than the limit in MaxResultRecords)|The selection returned more records than the limit",like(err_message,"ERROR_CODE 4531 Failed to get metadata from LOB service%"),"(ERROR_CODE 4531 Failed to get metadata from LOB service)|Invalid Node Id",like(err_message,"ERROR_CODE 4537 Cannot get tenant connection details%"),"(ERROR_CODE 4537 Cannot get tenant connection details)|(UNKNOWN ERROR) ERROR_CODE 4537 Cannot get tenant connection details",like(err_message,"ERROR_CODE 4544 Server error in Read audit log request%"),"(ERROR_CODE 4544 Server error in Read audit log request)|(UNKNOWN ERROR) ERROR_CODE 4544 Server error in Read audit log request",like(err_message,"ERROR_CODE 4545 Metadata Server Error%"),"(ERROR_CODE 4545 Metadata Server Error)|(UNKNOWN ERROR) ERROR_CODE 4545 Metadata Server Error",like(err_message,"ERROR_CODE 4546 Forbidden Metadata Response Error%"),"(ERROR_CODE 4546 Forbidden Metadata Response Error)|(UNKNOWN ERROR) ERROR_CODE 4546 Forbidden Metadata Response Error",like(err_message,"ERROR_CODE 4555 Writing to audit log failed%"),"(ERROR_CODE 4555 Writing to audit log failed)|(UNKNOWN ERROR) ERROR_CODE 4555 Writing to audit log failed",like(err_message,"ERROR_CODE 4558 Error creating DB connection%"),"(ERROR_CODE 4558 Error creating DB connection)|(UNKNOWN ERROR) ERROR_CODE 4558 Error creating DB connection",like(err_message,"ERROR_CODE 4562 v2/preexecutionmetadata response%"),"(ERROR_CODE 4562 v2/preexecutionmetadata response failed)|(UNKNOWN ERROR) ERROR_CODE 4562 v2/preexecutionmetadata response",like(err_message,"ERROR_CODE 6002 We failed to execute the query%"),"(ERROR_CODE 6002 We failed to execute the query)|(UNKNOWN ERROR) Failed to execute query",like(err_message,"ERROR_CODE 6006 Error while injecting%"),"(ERROR_CODE 6006 Error while injecting)|(UNKNOWN ERROR) ERROR_CODE 6006 Error while injecting ExtendedDimensions",like(err_message,"ERROR_CODE 6009 Unsupported dimension name in the query%"),"(ERROR_CODE 6009 Unsupported dimension name in the query)|(UNKNOWN ERROR) ERROR_CODE 6009 Unsupported dimension name in the query",like(err_message,"ERROR_CODE 6013 We found an unsupported query type%"),"(ERROR_CODE 6013 We found an unsupported query type)|(UNKNOWN ERROR) ERROR_CODE 6013 We found an unsupported query type",like(err_message,"ERROR_CODE 6016 We found an error while executing the SQL statement%"),"(ERROR_CODE 6016 We found an error while executing the SQL statement)|(UNKNOWN ERROR) ERROR_CODE 6016 We found an error while executing the SQL statement",like(err_message,"ERROR_CODE5037\"Column does not exist in calculation View\"%"),"(ERROR_CODE5037\"Column does not exist in calculation View\")|Column does not exist",like(err_message,"ERROR_CODE5040 Query is not activated and will be deleted%"),"(ERROR_CODE5040 Query is not activated and will be deleted)|Query is not activated",like(err_message,"ERROR_CODE5041 Query is not activated and will be reverted%"),"(ERROR_CODE5041 Query is not activated and will be reverted)|Query is not activated",like(err_message,"ERROR-5016 Source Field%does not exists%"),"(ERROR-5016 Source Field does not exists)|Data source",like(err_message,"ERROR-5028 Right datasource%is used in two joins"),"(ERROR-5028 Right datasource is used in two joins)|Data source join",like(err_message,"ERROR-5031 OutputField%not exists"),"(ERROR-5031 OutputField not exists)|(UNKNOWN ERROR) ERROR-5031 OutputField not exists",like(err_message,"ERROR-6002: LogicalModelName is null/empty%"),"(ERROR-6002: LogicalModelName is null/empty)|Logical Model Null",like(err_message,"Exception while getting DBPool"),"(Exception while getting DBPool)|(UNKNOWN ERROR) Exception while getting DBPool",like(err_message,"Exception while processing variables"),"(Exception while processing variables)|Exception while processing variables",like(err_message,"Export failed as variables definition is missing or invalid%"),"(Export failed as variables definition is missing or invalid)|(UNKNOWN ERROR) Export failed",like(err_message,"Fail to create%object%"),"(Fail to create object)|(UNKNOWN ERROR) Fail to create object",like(err_message,"Failed to get the server information%"),"(Failed to get the server information)|Failed to get the server information",like(err_message,"Failed to update job status%"),"(Failed to update job status)|(UNKNOWN ERROR) Failed to update object",like(err_message,"Forwarding to error page from request%"),"(Forwarding to error page from request)|(UNKNOWN ERROR) Request was rejected",like(err_message,"Getting secrets from vault failed during initial load"),"(Getting secrets from vault failed during initial load)|(UNKNOWN ERROR) Getting secrets failed",like(err_message,"%NullPointerException: while trying to invoke the method%"),"(NullPointerException: while trying to invoke the method)|NullPointer",like(err_message,"%RuntimeException: Cannot end scope%"),"(RuntimeException: Cannot end scope)|(UNKNOWN ERROR) RuntimeException: Cannot end scope",like(err_message,"%SQLException: Connection has already been closed%"),"(SQLException: Connection has already been closed)|SQLException: Connection has already been closed",like(err_message,"%SQLException: PooledConnection has already been closed%"),"(SQLException: PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"%JDBCDriverException%cannot allocate enough memory%"),"(JDBCDriverException: cannot allocate enough memory)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [4]: cannot allocate enough memory",like(err_message,"%DatabaseException: Error executing SQL%"),"(DatabaseException: Error executing SQL)|(UNKNOWN ERROR) DatabaseException: Error executing SQL",like(err_message,"%SQLException: PooledConnection has already been closed%"),"(SQLException: PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"%JDBCDriverException%cannot allocate enough memory%"),"(JDBCDriverException: cannot allocate enough memory)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [4]: cannot allocate enough memory",like(err_message,"%SQLException: PooledConnection has already been closed%"),"(SQLException: PooledConnection has already been closed )|PooledConnection has already been closed",like(err_message,"%SQLException: PooledConnection has already been closed%"),"(SQLException: PooledConnection has already been closed)|PooledConnection has already been closed",like(err_message,"Metadata missing for object%"),"(Metadata missing for object)|(UNKNOWN ERROR) Metadata missing",like(err_message,"Migration failed for query%"),"(Migration failed for query)|(UNKNOWN ERROR) Migration failed",like(err_message,"No matching output column found%"),"(No matching output column found)|(UNKNOWN ERROR) No matching output column found",like(err_message,"Node list not valid%"),"(Node list not valid)|(UNKNOWN ERROR) Node list not valid",like(err_message,"PackageName%does not have the correct naming convention%"),"(PackageName does not have the correct naming convention)|Package Naming",like(err_message,"PreparedStatementCallback%"),"(PreparedStatementCallback)|(UNKNOWN ERROR) PreparedStatementCallback error",like(err_message,"Query definition missing%"),"(Query definition missing)|(UNKNOWN ERROR) Query definition missing",like(err_message,"Query is not allowed since data for sensitive column%"),"(Query is not allowed since data for sensitive column)|(UNKNOWN ERROR) Query is not allowed",like(err_message,"Query result has errors while exporting the widget%"),"(Query result has errors while exporting the widget)|(UNKNOWN ERROR) Query result has errors",like(err_message,"QueryObject creation failed%"),"(QueryObject creation failed)|(UNKNOWN ERROR) QueryObject creation failed",like(err_message,"Remote API error response could not be parsed%"),"(Remote API error response could not be parsed)|(UNKNOWN ERROR) Remote API error response could not be parsed",like(err_message,"Remote API response error%"),"(Remote API response error)|Invalid Node Id",like(err_message,"REMOTE_API_RESPONSE_ERROR "),"(REMOTE_API_RESPONSE_ERROR )|Remote API Error",like(err_message,"Rest Client Exception Occurred%"),"(Rest Client Exception Occurred)|ResourceAccessException",like(err_message,"SAP DBTech JDBC: Object is closed%"),"(SAP DBTech JDBC: Object is closed)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: Object is closed",like(err_message,"SF API Returned error. Code: 4531%"),"(SF API Returned error. Code: 4531 Failed to get metadata)|Invalid Node Id",like(err_message,"SFSF Metadata child node list is empty%"),"(SFSF Metadata child node list is empty)|Child Node empty",like(err_message,"The parallel execution limit per tenant has been exceeded%"),"(The parallel execution limit per tenant has been exceeded)|Parallel execution limit per tenant has been exceeded",like(err_message,"Unable to get data from publicAPI service"),"(Unable to get data from publicAPI service)|Public API Error",like(err_message,"Uncaught underlying exception%"),"(Uncaught underlying exception)|(UNKNOWN ERROR) Uncaught underlying exception",like(err_message,"Unexpected error occured%IOException: error 104 - Connection reset by peer%"),"(Unexpected error occured IOException: error 104 - Connection reset by peer)|IOException: Connection reset by peer",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [139]: current operation cancelled by request and transaction rolled back"),"(Unexpected error occured SAP DBTech JDBC: [139]: current operation cancelled by request and transaction rolled back)|(UNKNOWN ERROR) JDBCDriverException: [139]: current operation cancelled by request and transaction rolled back",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [2]: general error: object name already exists%"),"(Unexpected error occured SAP DBTech JDBC: [2]: general error)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [2]: general error",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [2048]: column store error%"),"(Unexpected error occured SAP DBTech JDBC: [2048]: column store error)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [2048]: column store error",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [258]: insufficient privilege%"),"(Unexpected error occured SAP DBTech JDBC: [258]: insufficient privilege)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [258]: insufficient privilege",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [274]: inserted value too large for column%"),"(Unexpected error occured SAP DBTech JDBC: [274]: inserted value too large for column)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [274]: inserted value too large for column",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [3]: fatal error%"),"(Unexpected error occured SAP DBTech JDBC: [3]: fatal error)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [3]: fatal error",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [328]: invalid name of function or procedure%"),"(Unexpected error occured SAP DBTech JDBC: [328]: invalid name of function or procedure)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [328]: invalid name of function or procedure",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [391]: invalidated view%"),"(Unexpected error occured SAP DBTech JDBC: [391]: invalidated view)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [391]: invalidated view",like(err_message,"Unexpected error occured%SAP DBTech JDBC: [4]: cannot allocate enough memory%"),"(Unexpected error occured SAP DBTech JDBC: [4]: cannot allocate enough memory)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [4]: cannot allocate enough memory",like(err_message,"Unexpected error occured%SAP DBTech JDBC: Object is closed%"),"(Unexpected error occured SAP DBTech JDBC: Object is closed)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: Object is closed",like(err_message,"Unexpected error occured%SQLNonTransientConnectionExceptionSapDB: Connection to database server lost%"),"(Unexpected error occured SQLNonTransientConnectionExceptionSapDB: Connection to database server lost)|IOException: Connection reset by peer",like(err_message,"Unexpected error occured%SQLTransactionRollbackExceptionSapDB: [129]: transaction rolled back by an internal error%"),"(Unexpected error occured SQLTransactionRollbackExceptionSapDB: [129]: transaction rolled back by an internal error)|(UNKNOWN ERROR) SQLTransactionRollbackExceptionSapDB: [129]: transaction rolled back by an internal error",like(err_message,"Unexpected error occured%DatabaseException Internal Exception%"),"(Unexpected error occured DatabaseException Internal Exception)|(UNKNOWN ERROR) Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.5.v20170607-b3d05bd)",like(err_message,"Unexpected error occured: java.lang.ArrayIndexOutOfBoundsException%"),"(Unexpected error occured: java.lang.ArrayIndexOutOfBoundsException)|ArrayIndexOutOfBoundsException",like(err_message,"Unexpected error occured: java.lang.IndexOutOfBoundsException%"),"(Unexpected error occured: java.lang.IndexOutOfBoundsException)|IndexOutOfBoundsException",like(err_message,"Unexpected error occured: java.lang.NullPointerException%"),"(Unexpected error occured: java.lang.NullPointerException)|NullPointer",like(err_message,"Unexpected error occured%DatabaseException Internal Exception%"),"(Unexpected error occured DatabaseException Internal Exception)|(UNKNOWN ERROR) Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.5.v20170607-b3d05bd)",like(err_message,"Unexpected error occured%IOException: error 104 - Connection reset by peer"),"(Unexpected error occured IOException: error 104 - Connection reset by peer)|IOException: Connection reset by peer",like(err_message,"Unexpected error occured%ResourceFailureException: PreparedStatementCallback%"),"(Unexpected error occured ResourceFailureException: PreparedStatementCallback)|(UNKNOWN ERROR) DataAccessResourceFailureException: PreparedStatementCallback",like(err_message,"Unexpected error occured%UncategorizedSQLException: PreparedStatementCallback%"),"(Unexpected error occured UncategorizedSQLException: PreparedStatementCallback)|(UNKNOWN ERROR) UncategorizedSQLException: PreparedStatementCallback",like(err_message,"Unexpected error occured%DatabaseException Internal Exception%"),"(Unexpected error occured DatabaseException Internal Exception)|(UNKNOWN ERROR) JpaSystemException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.5.v20170607-b3d05bd)",like(err_message,"Unexpected error occured%TransactionSystemException: Could not commit JPA transaction%"),"(Unexpected error occured%TransactionSystemException: Could not commit JPA transaction)|(UNKNOWN ERROR) TransactionSystemException: Could not commit JPA transaction",like(err_message,"Unexpected error occured%HttpServerErrorException$$ServiceUnavailable: 503 Service Unavailable%"),"(Unexpected error occured HttpServerErrorException$$ServiceUnavailable: 503 Service Unavailable)|(UNKNOWN ERROR) HttpServerErrorException$$ServiceUnavailable: 503 Service Unavailable",like(err_message,"Unexpected error occured%ResourceAccessException: I/O error on GET request%"),"(Unexpected error occured ResourceAccessException: I/O error on GET request)|(UNKNOWN ERROR) ResourceAccessException: I/O error on GET request",like(err_message,"Unexpected error occured%UnknownHttpStatusCodeException: 555%"),"(Unexpected error occured UnknownHttpStatusCodeException: 555)|(UNKNOWN ERROR) UnknownHttpStatusCodeException: 555 HTTP standard status code",like(err_message,"Unexpected error occured%NestedServletException: Handler dispatch failed%"),"(Unexpected error occured NestedServletException: Handler dispatch failed)|(UNKNOWN ERROR) NestedServletException: Handler dispatch failed",like(err_message,"Unhandled error in servlet filter processing%"),"(Unhandled error in servlet filter processing)|Unhandled Error",like(err_message,"Unrecognized field \"isBaseDataSource\"%"),"(Unrecognized field \"isBaseDataSource\")|(UNKNOWN ERROR) Unrecognized field",like(err_message,"Unrecognized field \"sourceDataSourceIdFormated\"%"),"(Unrecognized field \"sourceDataSourceIdFormated\")|(UNKNOWN ERROR) Unrecognized field",like(err_message,"VCAP_SERVICES is valid JSON, but not a JSON object%"),"(VCAP_SERVICES is valid JSON, but not a JSON object)|VCAP_SERVICES not a valid JSON",like(err_message,"We failed to execute the query%"),"(We failed to execute the query)|(UNKNOWN ERROR) Failed to execute query",like(err_message,"while trying to invoke the method com.sap.firefly.core.parameter.IPrElement.isStructure()%"),"(while trying to invoke the method com.sap.firefly.core.parameter.IPrElement.isStructure())|(UNKNOWN ERROR) Null object",like(err_message,"while trying to invoke the method com.sap.firefly.olap.manager.IQueryManager.setMaxResultRecords(long)%"),"(while trying to invoke the method com.sap.firefly.olap.manager.IQueryManager.setMaxResultRecords(long))|(UNKNOWN ERROR) Null object",like(err_message,"while trying to invoke the method java.sql.Timestamp.compareTo(java.sql.Timestamp)%"),"(while trying to invoke the method java.sql.Timestamp.compareTo(java.sql.Timestamp))|(UNKNOWN ERROR) Null object",like(err_message,"while trying to invoke the method liquibase.logging.LogService.getLog(java.lang.Class)%"),"(while trying to invoke the method liquibase.logging.LogService.getLog(java.lang.Class))|(UNKNOWN ERROR) Null object",like(err_message,"Index:%, Size:%"),"(Index:..., Size:)|(UNKNOWN ERROR) Index: 0, Size: 0",like(err_message,"null"),"(null)|(UNKNOWN ERROR) Logical Model Null",like(err_message,"Unexpected error occured%IOException: error 32 - Broken pipe"),"(Unexpected error occured IOException: error 32 - Broken pipe)|IOException: Broken pipe",like(err_message,"SAP DBTech JDBC: [597]: session context error%"),"(SAP DBTech JDBC: [597]: session context error)|(UNKNOWN ERROR) SAP DBTech JDBC: [597]: session context error",like(err_message,"%Unexpected error occurred%IOException: error 32 - Broken pipe"),"(Unexpected error occurred IOException: error 32 - Broken pipe)|IOException: Broken pipe",like(err_message,"504 Gateway Time-out%"),"(504 Gateway Time-out)|(UNKNOWN ERROR) 504 Gateway Time-out",like(err_message,"ERROR_CODE 42522 No values set for mandatory variable%"),"(ERROR_CODE 42522 No values set for mandatory variable)|(UNKNOWN ERROR) ERROR_CODE 42522 No values set for mandatory variable",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [597]: session context error%"),"(Unexpected error occurred SAP DBTech JDBC: [597]: session context error)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [597]: session context error",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [601]: too many session variables are set%"),"(Unexpected error occurred SAP DBTech JDBC: [601]: too many session variables are set)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [601]: too many session variables are set",like(err_message,"Unexpected error occurred%IOException: error 110 - Connection timed out%"),"(Unexpected error occurred IOException: error 110 - Connection timed out)|(UNKNOWN ERROR) IOException: error 110 - Connection timed out",like(err_message,"%Unexpected error occurred%IOException: error 32 - Broken pipe"),"(Unexpected error occurred IOException: error 32 - Broken pipe)|IOException: Broken pipe",like(err_message,"401 : \"Wrapper token invalid\""),"(401 : \"Wrapper token invalid\")|(UNKNOWN ERROR) 401 : \"Wrapper token invalid\"",like(err_message,"500 : \"Internal server error%"),"(500 : \"Internal server error)|(UNKNOWN ERROR) 500 : \"Internal server error, please contact administrator\"",like(err_message,"504 Gateway Time-out"),"(504 Gateway Time-out)|504 Gateway Time-out",like(err_message,"Data receive failed%error 104 - Connection reset by peer%"),"(Data receive failed error 104 - Connection reset by peer)|IOException: Connection reset by peer",like(err_message,"Error occured during initial fetching x509 certificate  for vault"),"(Error occured during initial fetching x509 certificate  for vault)|(UNKNOWN ERROR) Error occured during initial fetching x509 certificate",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42017: Not authorized%"),"(ERROR_CODE 42014 Caught exception : exception 42017: Not authorized)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception : exception 42017: Not authorized",like(err_message,"ERROR_CODE 42014 Caught exception : exception 42248: A cube operation failed%"),"(ERROR_CODE 42014 Caught exception : exception 42248: A cube operation failed)|(UNKNOWN ERROR) ERROR_CODE 42014 Caught exception : exception 42248: A cube operation failed",like(err_message,"ERROR_CODE 42024 An expected attribute is missing%"),"(ERROR_CODE 42024 An expected attribute is missing)|(UNKNOWN ERROR) ERROR_CODE 42024 An expected attribute is missing",like(err_message,"ERROR_CODE 42432 Dimension attribute referenced in view is not defined%"),"(ERROR_CODE 42432 Dimension attribute referenced in view is not defined)|(UNKNOWN ERROR) ERROR_CODE 42432 Dimension attribute referenced in view is not defined",like(err_message,"ERROR_CODE 42522 No values set for mandatory variable"),"(ERROR_CODE 42522 No values set for mandatory variable)|(UNKNOWN ERROR) ERROR_CODE 42522 No values set for mandatory variable",like(err_message,"ERROR-5008 Fields are empty in QueryScenarioDataSource%"),"(ERROR-5008 Fields are empty in QueryScenarioDataSource)|(UNKNOWN ERROR) ERROR-5008 Fields are empty in QueryScenarioDataSource",like(err_message,"Fail to get MDS heart beat information%"),"(Fail to get MDS heart beat information)|(UNKNOWN ERROR) Fail to get MDS heart beat information",like(err_message,"Liquibase process failed due to incompatible column datatypes%"),"(Liquibase process failed due to incompatible column datatypes)|(UNKNOWN ERROR) Liquibase process failed due to incompatible column datatypes",like(err_message,"%JDBCDriverException: SAP DBTech JDBC: [600]: failed routed execution%"),"(JDBCDriverException: SAP DBTech JDBC: [600]: failed routed execution)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [600]: failed routed execution",like(err_message,"%JDBCDriverException: SAP DBTech JDBC: Object is closed%"),"(JDBCDriverException: SAP DBTech JDBC: Object is closed)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: Object is closed",like(err_message,"SAP DBTech JDBC: [2566]: distributed environment error%"),"(SAP DBTech JDBC: [2566]: distributed environment error)|(UNKNOWN ERROR) SAP DBTech JDBC: [2566]: distributed environment erro",like(err_message,"SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel%"),"(SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel)|(UNKNOWN ERROR) SAP DBTech JDBC: [2567]: network error",like(err_message,"SAP DBTech JDBC: [2567]: network error: the application threw an exception%"),"(SAP DBTech JDBC: [2567]: network error: the application threw an exception)|(UNKNOWN ERROR) SAP DBTech JDBC: [2567]: network error",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [145]: transaction distribution work failure%"),"(Unexpected error occurred SAP DBTech JDBC: [145]: transaction distribution work failure)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [145]: transaction distribution work failure",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [2566]: distributed environment error%"),"(Unexpected error occurred SAP DBTech JDBC: [2566]: distributed environment error)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [2566]: distributed environment error",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel"),"(Unexpected error occurred SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [2567]: network error",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [2567]: network error: the application threw an exception"),"(Unexpected error occurred SAP DBTech JDBC: [2567]: network error: the application threw an exception)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [2567]: network error",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure%"),"(Unexpected error occurred SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure",like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [601]: too many session variables are set%"),"(Unexpected error occurred SAP DBTech JDBC: [601]: too many session variables are set)|(UNKNOWN ERROR) JDBCDriverException: SAP DBTech JDBC: [601]: too many session variables are set",like(err_message,"Unexpected error occurred%URLDecoder: Illegal hex characters%"),"(Unexpected error occurredURLDecoder: Illegal hex characters)|(UNKNOWN ERROR) IllegalArgumentException: URLDecoder: Illegal hex characters",like(err_message,"Unexpected error occurred%URLDecoder: Incomplete trailing escape%"),"(Unexpected error occurred URLDecoder: Incomplete trailing escape)|(UNKNOWN ERROR) IllegalArgumentException: URLDecoder: Incomplete trailing escape",like(err_message,"Unexpected error occurred%Timeout: Pool empty. Unable to fetch a connection%"),"(Unexpected error occurred Timeout: Pool empty. Unable to fetch a connection)|(UNKNOWN ERROR) PoolExhaustedException",like(err_message,"%%"),"(Blank)|(UNKNOWN ERROR)",1==1,err_message)

| eval temp=split(err_message, "|")
| eval err_message=mvindex(temp,0)
| eval errorType=mvindex(temp,1) | fields - temp
| eval date = strftime(_time, "%Y-%m-%d") 
| eval weekday = strftime(_time, "%A") 
| eval time = strftime(_time, "%H:%M") 
| eval hour = "\"" + substr(time,1,2) + "\""
| eval minute = strftime(_time, "%M")
| eval time_2 = strftime(_time + if(minute%2=0,0,(2-minute%2)*60), "%H:%M")
| eval time_3 = strftime(_time + if(minute%3=0,0,(3-minute%3)*60), "%H:%M")
| eval date_2 = strftime(_time + if(time="23:59",86400,0), "%Y-%m-%d")
| eval date_3 = strftime(_time + if(time="23:58" OR time="23:59",86400,0), "%Y-%m-%d") | fields - minute
| eval server = if(servername!="", servername, host)
| eval server_type = if (substr(server, 1, 2) = "pc", "PROD", if (substr(server, 1, 2) = "sc", "PREVIEW", if (substr(server, 1, 2) = "ac", "QA",if (substr(server, 1, 2) = "ps", "SALES DEMO", "OTHER") ) ) ) 
| eval sac_app_correlation_id=replace(sac_app_correlation_id, "\-" , "")

| eval skip=substr(skip, 1, 256) | eval err_message=substr(err_message, 1, 256)

| eval id=1 | accum id | eval count=1

| rename SFDC AS "dc", sac_app_company_id as "instance", sac_app_correlation_id as "correl", component as errorClass, err_message as errorCategory

| eval tempTime = strftime(_time, "%H:%M:%S") | dedup instance, date, tempTime, correl | fields - tempTime

| table id, date, weekday, time, hour, dc, sourcetype, server, server_type, instance, correl, errorClass, errorCategory, errorType, count, time_2, date_2, time_3, date_3
